# Generated by Django 5.2.10 on 2026-01-12 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('target_country_code', models.CharField(default='ES', max_length=10)),
                ('language_code', models.CharField(default='es', max_length=10)),
                ('gsc_property_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ga4_property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_ads_customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
            ],
        ),
    ]
