# Generated by Django 5.2.10 on 2026-01-18 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('target_country_code', models.CharField(default='ES', max_length=10)),
                ('language_code', models.CharField(default='es', max_length=10)),
                ('gsc_property_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ga4_property_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_ads_customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('authorized_monthly_budget', models.DecimalField(decimal_places=2, default=50.0, help_text='Presupuesto máximo mensual para APIs de pago (SerpAPI/DataForSEO).', max_digits=10)),
                ('gsc_verified', models.BooleanField(default=False)),
                ('ga4_verified', models.BooleanField(default=False)),
                ('ads_verified', models.BooleanField(default=False)),
                ('last_integration_check', models.DateTimeField(blank=True, null=True)),
                ('preferred_serp_provider', models.CharField(choices=[('serpapi', 'SerpAPI'), ('dataforseo', 'DataForSEO')], default='serpapi', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('google_credential', models.ForeignKey(blank=True, help_text='Service Account para GSC, GA4 y Ads', null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.googlecredential')),
            ],
        ),
        migrations.CreateModel(
            name='GscRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('page', models.URLField(blank=True, max_length=1000, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('impressions', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsc_data', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'date', 'query', 'page')},
            },
        ),
    ]
