# Generated by Django 6.0.1 on 2026-01-22 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_googlecredential_name_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gscrow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='authorized_monthly_budget',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='google_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.googlecredential'),
        ),
        migrations.AddConstraint(
            model_name='gscrow',
            constraint=models.UniqueConstraint(fields=('project', 'date', 'query', 'page'), name='unique_gsc_row_record'),
        ),
    ]
