# Generated by Django 5.2.10 on 2026-01-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_credential',
            field=models.ForeignKey(blank=True, help_text='Service Account para GSC, GA4 y Ads', null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.googlecredential'),
        ),
    ]
