# Generated by Django 5.2.10 on 2026-01-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_google_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authorized_monthly_budget',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Presupuesto máximo mensual para APIs de pago (SerpAPI/DataForSEO).', max_digits=10),
        ),
    ]
