# Generated by Django 5.2.10 on 2026-01-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_authorized_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ads_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ga4_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='gsc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='last_integration_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
