# Generated by Django 5.2.10 on 2026-01-12 02:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=100)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('cost_units', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
