# Generated by Django 5.2.10 on 2026-01-18 00:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=100)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('cost_units', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('outputs', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
