# Generated by Django 6.0.1 on 2026-01-22 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_timezone'),
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='run',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_runs', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='run',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En proceso'), ('SUCCESS', 'Éxito'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='run',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['project', 'status', 'created_at'], name='core_run_project_59397c_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['input_hash', 'kind', 'status'], name='core_run_input_h_771328_idx'),
        ),
    ]
