# Generated by Django 5.2.10 on 2026-01-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_contact_name_client_email_client_phone_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='raw_response',
            new_name='raw_json',
        ),
        migrations.AddField(
            model_name='run',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AddField(
            model_name='run',
            name='inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='run',
            name='input_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
