# Generated by Django 5.2.10 on 2026-01-18 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsLanguage',
            fields=[
                ('criteria_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='ISO Code (en, es, fr)', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoogleAdsLocation',
            fields=[
                ('criteria_id', models.BigIntegerField(help_text='Google GeoTarget ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('canonical_name', models.CharField(db_index=True, max_length=500)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('target_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Google Ads Location',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KeywordIdeaRun',
            fields=[
                ('run_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.run')),
                ('seed_keyword', models.CharField(blank=True, help_text='Keyword semilla o descripción del import', max_length=255, null=True)),
                ('country_code', models.CharField(default='US', max_length=10)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('source', models.CharField(default='database', help_text="ej: 'google_ads', 'dataforseo', 'csv_import'", max_length=50)),
                ('items_found', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Keyword Run',
                'verbose_name_plural': 'Keyword Runs',
            },
            bases=('core.run',),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(db_index=True, max_length=255)),
                ('last_vol', models.IntegerField(default=0)),
                ('last_cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_intent', models.CharField(blank=True, choices=[('informational', 'Informational'), ('navigational', 'Navigational'), ('commercial', 'Commercial'), ('transactional', 'Transactional')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_keywords', to='projects.project')),
            ],
            options={
                'ordering': ['-last_vol'],
                'unique_together': {('project', 'normalized_text')},
            },
        ),
        migrations.CreateModel(
            name='KeywordStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Estrategia Principal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_text', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=3)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keyword_research.keywordstrategy')),
                ('tracked_keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keyword_research.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_volume', models.BigIntegerField(blank=True, default=0, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('competition', models.FloatField(blank=True, help_text='0.0 a 1.0', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='keyword_research.keywordidearun')),
            ],
            options={
                'verbose_name': 'Keyword Idea',
                'indexes': [models.Index(fields=['run', 'keyword'], name='keyword_res_run_id_476c1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordMetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('search_volume', models.IntegerField(default=0)),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='keyword_research.keyword')),
            ],
            options={
                'ordering': ['-date_recorded'],
                'unique_together': {('keyword', 'date_recorded')},
            },
        ),
        migrations.CreateModel(
            name='URLAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=100, null=True)),
                ('in_sitemap', models.BooleanField(default=False)),
                ('sitemap_status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_inspected', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audited_urls', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'url')},
            },
        ),
    ]
