# Generated by Django 6.0.1 on 2026-01-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0001_initial'),
        ('projects', '0002_alter_gscrow_unique_together_project_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleadslanguage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordidea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keywordidearun',
            options={'verbose_name': 'Keyword Run'},
        ),
        migrations.AlterModelOptions(
            name='keywordmetricsnapshot',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='keywordmetricsnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='urlaudit',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='googleadslanguage',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='googleadslocation',
            name='criteria_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keywordidea',
            name='competition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='keywordidearun',
            name='seed_keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='keywordidearun',
            name='source',
            field=models.CharField(default='database', max_length=50),
        ),
        migrations.AlterField(
            model_name='keywordstrategy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='urlaudit',
            index=models.Index(fields=['project', 'url'], name='keyword_res_project_6adffa_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('project', 'normalized_text'), name='unique_keyword_project'),
        ),
        migrations.AddConstraint(
            model_name='keywordmetricsnapshot',
            constraint=models.UniqueConstraint(fields=('keyword', 'date_recorded'), name='unique_metric_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='urlaudit',
            constraint=models.UniqueConstraint(fields=('project', 'url'), name='unique_url_audit_per_project'),
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='last_intent',
        ),
    ]
