# Generated by Django 5.2.10 on 2026-01-13 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0001_initial'),
        ('projects', '0002_project_google_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_inspected', models.DateTimeField(auto_now=True)),
                ('verdict', models.CharField(blank=True, max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
