# Generated by Django 5.2.10 on 2026-01-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0002_urlaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaudit',
            name='indexing_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
