# Generated by Django 5.2.10 on 2026-01-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0003_urlaudit_indexing_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlaudit',
            name='sitemap_status',
            field=models.CharField(blank=True, help_text='Estado reportado por GSC (ej: Success, No se pudo obtener)', max_length=100, null=True),
        ),
    ]
