# Generated by Django 5.2.10 on 2026-01-14 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0004_urlaudit_sitemap_status'),
        ('projects', '0002_project_google_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Estrategia Principal', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('volume', models.IntegerField(default=0)),
                ('intent', models.CharField(blank=True, max_length=50)),
                ('priority', models.IntegerField(default=3)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='keyword_research.keywordstrategy')),
            ],
        ),
    ]
