# Generated by Django 5.2.10 on 2026-01-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0005_keywordstrategy_strategyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsLocation',
            fields=[
                ('criteria_id', models.BigIntegerField(help_text='Google GeoTarget ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('canonical_name', models.CharField(db_index=True, max_length=500)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('country_code', models.CharField(db_index=True, max_length=10)),
                ('target_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Google Ads Location',
                'ordering': ['name'],
            },
        ),
    ]
