# Generated by Django 5.2.10 on 2026-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0006_googleadslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsLanguage',
            fields=[
                ('criteria_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='ISO Code (en, es, fr)', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
