# Generated by Django 5.2.10 on 2026-01-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0007_googleadslanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordidea',
            name='competition_index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='keywordidea',
            name='cpc',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True),
        ),
    ]
