# Generated by Django 5.2.10 on 2026-01-12 21:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Ej: 'SA Principal Daniel' o 'Cliente X'", max_length=255)),
                ('service_account_json', models.JSONField(help_text='Pega aquí el contenido íntegro del archivo .json descargado de Google Cloud')),
                ('client_email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
