# Generated by Django 6.0.1 on 2026-01-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredential',
            name='name',
            field=models.CharField(help_text="Ej: 'SA Principal Daniel'", max_length=255),
        ),
        migrations.AlterField(
            model_name='googlecredential',
            name='service_account_json',
            field=models.JSONField(help_text='Contenido íntegro del archivo .json de Google Cloud'),
        ),
    ]
