# Generated by Django 5.2.10 on 2026-01-18 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0001_initial'),
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serpsnapshot',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keyword_research.keywordidea'),
        ),
    ]
