# Generated by Django 6.0.1 on 2026-01-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0002_alter_googleadslanguage_options_and_more'),
        ('projects', '0002_alter_gscrow_unique_together_project_status_and_more'),
        ('serp', '0002_serpsnapshot_idea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serpsnapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'SERP Snapshot'},
        ),
        migrations.AlterField(
            model_name='serpsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serp_snapshots', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='serpsnapshot',
            index=models.Index(fields=['input_hash', 'created_at'], name='serp_serpsn_input_h_d23213_idx'),
        ),
        migrations.AddIndex(
            model_name='serpsnapshot',
            index=models.Index(fields=['project', 'keyword'], name='serp_serpsn_project_c3458d_idx'),
        ),
    ]
