# Generated by Django 5.2.10 on 2026-01-13 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_research', '0003_urlaudit_indexing_requested_at'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keyword_research.urlaudit'),
        ),
    ]
